"""
Add missing E-7-2, E-7-3, E-7-S, E-7-Y and other missing rows to 정리.xlsx MASTER_ROWS sheet.
Run from repo root: python analysis/클로드/서버설정/add_missing_rows.py
"""
import sys, os
sys.stdout.reconfigure(encoding='utf-8')
import openpyxl

EXCEL_PATH = os.path.join(os.path.dirname(__file__), '..', '정리.xlsx')

new_rows = [
    # ─────────────── E-7-2 준전문인력 ───────────────
    {
        'row_id': 'M1-0310',
        'domain': '체류민원',
        'major_action_std': '체류자격 변경허가',
        'action_type': 'CHANGE',
        'business_name': '준전문인력',
        'detailed_code': 'E-7-2',
        'overview_short': '사무 및 서비스 분야 준전문인력 직종(E-7-2)에 종사하려는 외국인의 체류자격 변경 업무',
        'form_docs': '통합신청서(별지34호서식) | 위임장 | 대행업무수행확인서 | 외국인 직업 신고서',
        'supporting_docs': '여권 | 증명사진 1장(최근 6개월 이내, 흰색 배경) | 외국인등록증 | 고용계약서 | 신원보증서 | 납부내역증명(납세사실증명) | 납세증명서(국세완납증명) | 지방세납세증명서 | 사업자등록증 | 고용추천서(해당자) | 체류지 입증서류(임대차계약서 등)',
        'exceptions_summary': 'E-7-2 준전문인력 10개 직종(사무종사자 5·서비스종사자 5) 범위 내에서만 허용 / 국민고용비율 준수 / 대기업 관리자는 고용추천서 징구 면제, 중소기업 관리자에 해당 시 징구 가능 / 체류 가능 합법 체류 자격에서 변경 가능',
        'fee_rule': '수수료 없음 (체류자격 변경허가)',
        'basis_file': '260310 체류민원 자격별 안내 매뉴얼.pdf',
        'basis_section': '출입국관리법 제24조|260310 체류민원 자격별 안내 매뉴얼 특정활동(E-7) 준전문인력(E-7-2)',
        'status': 'active',
    },
    {
        'row_id': 'M1-0311',
        'domain': '체류민원',
        'major_action_std': '체류기간 연장허가',
        'action_type': 'EXTEND',
        'business_name': '준전문인력',
        'detailed_code': 'E-7-2',
        'overview_short': '특정활동(E-7-2) 자격으로 준전문인력 활동을 계속하려는 외국인의 체류기간 연장 업무',
        'form_docs': '통합신청서(별지34호서식) | 위임장 | 대행업무수행확인서 | 외국인 직업 신고서',
        'supporting_docs': '여권 원본 | 외국인등록증 | 표준규격사진 1매 | 고용계약서 사본 또는 재직증명서 | 사업자등록증 | 체류지 입증서류 | 연간소득 입증서류(개인소득금액증명 필수) | 직종별 계속고용 요건 입증서류',
        'exceptions_summary': '특정활동(E-7)은 취업 가능 자격으로 직업 및 연간소득금액 신고 대상 / 여권 유효기간 범위 내 체류기간 부여 / 판매사무원 등 일부 직종은 신원보증서 징구 가능 / 결핵고위험국가 조건 해당 시 결핵진단서 추가 가능',
        'fee_rule': '수수료 없음 (체류기간 연장허가)',
        'basis_file': '260310 체류민원 자격별 안내 매뉴얼.pdf',
        'basis_section': '출입국관리법 제25조|260310 체류민원 자격별 안내 매뉴얼 특정활동(E-7) 준전문인력(E-7-2)',
        'status': 'active',
    },
    {
        'row_id': 'M1-0312',
        'domain': '체류민원',
        'major_action_std': '외국인등록',
        'action_type': 'REGISTRATION',
        'business_name': '준전문인력',
        'detailed_code': 'E-7-2',
        'overview_short': '특정활동(E-7-2) 자격으로 입국하거나 체류자격을 받은 외국인의 외국인등록 업무',
        'form_docs': '통합신청서(별지34호서식) | 위임장 | 외국인 직업 신고서',
        'supporting_docs': '여권 원본 | 표준규격사진 1매 | 사업자등록증 | 고용계약서 또는 재직예정 입증서류 | 체류지 입증서류 | 체류자격부여/변경 허가서 또는 입국 사증 | 신원보증인 신분증 | 납부내역증명(납세사실증명) | 납세증명서(국세완납증명) | 지방세납세증명서 | 학위증 또는 경력증명서',
        'exceptions_summary': '특정활동(E-7)은 외국인등록 시 직업 및 연간소득금액 신고 대상 / 만 6세~18세 재학 중인 경우 재학증명서 제출 / 결핵고위험국가 조건 해당 시 결핵진단서 추가 가능',
        'fee_rule': '외국인등록증 발급 및 재발급 3만 5천원',
        'basis_file': '260310 체류민원 자격별 안내 매뉴얼.pdf',
        'basis_section': '외국인등록|출입국관리법 시행규칙 제47조·제49조의2·제72조|260310 체류민원 자격별 안내 매뉴얼 특정활동(E-7) 준전문인력(E-7-2)',
        'status': 'active',
    },
    {
        'row_id': 'M1-0313',
        'domain': '체류민원',
        'major_action_std': '재입국허가',
        'action_type': 'REENTRY',
        'business_name': '준전문인력',
        'detailed_code': 'E-7-2',
        'overview_short': '특정활동(E-7-2) 자격의 재입국허가 업무',
        'form_docs': '통합신청서(별지34호서식) | 위임장',
        'supporting_docs': '여권 | 외국인등록증 | 고용계약서 | 신원보증인 신분증 | 납부내역증명(납세사실증명) | 납세증명서(국세완납증명) | 지방세납세증명서 | 학위증 또는 경력증명서 | 사업자등록증',
        'exceptions_summary': '등록을 필한 외국인이 출국한 날부터 1년 이내 재입국하려는 경우 재입국허가 면제 / 체류기간이 1년보다 적게 남아있는 경우 체류기간 범위 내 면제 / 입국규제자 및 사증발급규제자는 재입국허가 필요',
        'fee_rule': '단수 3만원 | 복수 5만원',
        'basis_file': '260310 체류민원 자격별 안내 매뉴얼.pdf',
        'basis_section': '재입국허가|260310 체류민원 자격별 안내 매뉴얼 공통 재입국허가',
        'status': 'active',
    },
    {
        'row_id': 'M1-0314',
        'domain': '체류민원',
        'major_action_std': '사증발급인정서',
        'action_type': 'VISA_CONFIRM',
        'business_name': '준전문인력',
        'detailed_code': 'E-7-2',
        'overview_short': '특정활동(E-7-2) 준전문인력 자격 사증발급인정서 발급 업무',
        'form_docs': '사증발급인정서 신청서(별지17호서식) | 위임장',
        'supporting_docs': '여권 사본 | 표준규격사진 1매 | 고용계약서 | 사업자등록증 | 고용추천서(해당자) | 학위증 또는 경력증명서 | 납부내역증명(납세사실증명) | 체류지 입증서류',
        'exceptions_summary': 'E-7-2 허용 직종 범위 내에서만 발급 / 국민고용비율 준수 여부 확인 / 재외공관에서 사증 신청 시 사증발급인정서 또는 심사 없이 진행 가능한 경우 있음',
        'fee_rule': '수수료 없음 (사증발급인정서)',
        'basis_file': '260310 체류민원 자격별 안내 매뉴얼.pdf',
        'basis_section': '사증발급인정서|260310 체류민원 자격별 안내 매뉴얼 특정활동(E-7) 준전문인력(E-7-2)',
        'status': 'active',
    },

    # ─────────────── E-7-3 일반기능인력 ───────────────
    {
        'row_id': 'M1-0315',
        'domain': '체류민원',
        'major_action_std': '체류자격 변경허가',
        'action_type': 'CHANGE',
        'business_name': '일반기능인력',
        'detailed_code': 'E-7-3',
        'overview_short': '일반기능인력 직종(E-7-3)에 종사하려는 외국인의 체류자격 변경 업무',
        'form_docs': '통합신청서(별지34호서식) | 위임장 | 대행업무수행확인서 | 외국인 직업 신고서',
        'supporting_docs': '여권 | 증명사진 1장(최근 6개월 이내, 흰색 배경) | 외국인등록증 | 고용계약서 | 신원보증서 | 납부내역증명(납세사실증명) | 납세증명서(국세완납증명) | 지방세납세증명서 | 사업자등록증 | 기량검증 확인서(해당 직종) | 고용추천서(산업통상자원부 등) | 체류지 입증서류',
        'exceptions_summary': 'E-7-3 일반기능인력 14개 직종(조선용접공·선박전기원·선박도장공·항공기정비원·항공기부품제조원·송전전기원·자동차부품제조원·자동차관금도장공·도축원·건설기계부품제조원 등) 범위 내 허용 / 기량검증이 필요한 직종은 산업부 지정기관의 현지 기량검증 통과 필수 / 국민고용비율 준수 / 사회통합프로그램 조건 적용(국내 입국 후 1년 이내)',
        'fee_rule': '수수료 없음 (체류자격 변경허가)',
        'basis_file': '260310 체류민원 자격별 안내 매뉴얼.pdf',
        'basis_section': '출입국관리법 제24조|260310 체류민원 자격별 안내 매뉴얼 특정활동(E-7) 일반기능인력(E-7-3)',
        'status': 'active',
    },
    {
        'row_id': 'M1-0316',
        'domain': '체류민원',
        'major_action_std': '체류기간 연장허가',
        'action_type': 'EXTEND',
        'business_name': '일반기능인력',
        'detailed_code': 'E-7-3',
        'overview_short': '특정활동(E-7-3) 자격으로 일반기능인력 활동을 계속하려는 외국인의 체류기간 연장 업무',
        'form_docs': '통합신청서(별지34호서식) | 위임장 | 대행업무수행확인서 | 외국인 직업 신고서',
        'supporting_docs': '여권 원본 | 외국인등록증 | 표준규격사진 1매 | 고용계약서 사본 또는 재직증명서 | 사업자등록증 | 체류지 입증서류 | 연간소득 입증서류(개인소득금액증명 필수) | 기량검증 확인서(해당 직종) | 직종별 계속고용 요건 입증서류',
        'exceptions_summary': '사회통합프로그램 이수 조건 적용(국내 입국 후 1년 이내 사전평가 21점 이상, 2단계 배정 또는 1단계 이수) / 근무처 변경은 휴·폐업, 경영악화 등 부득이한 경우에 한함 / 기량검증이 필요한 직종은 지속 요건 확인 / 결핵고위험국가 조건 해당 시 결핵진단서 추가 가능',
        'fee_rule': '수수료 없음 (체류기간 연장허가)',
        'basis_file': '260310 체류민원 자격별 안내 매뉴얼.pdf',
        'basis_section': '출입국관리법 제25조|260310 체류민원 자격별 안내 매뉴얼 특정활동(E-7) 일반기능인력(E-7-3)',
        'status': 'active',
    },
    {
        'row_id': 'M1-0317',
        'domain': '체류민원',
        'major_action_std': '외국인등록',
        'action_type': 'REGISTRATION',
        'business_name': '일반기능인력',
        'detailed_code': 'E-7-3',
        'overview_short': '특정활동(E-7-3) 자격으로 입국하거나 체류자격을 받은 외국인의 외국인등록 업무',
        'form_docs': '통합신청서(별지34호서식) | 위임장 | 외국인 직업 신고서',
        'supporting_docs': '여권 원본 | 표준규격사진 1매 | 사업자등록증 | 고용계약서 | 체류지 입증서류 | 체류자격부여/변경 허가서 또는 입국 사증 | 신원보증인 신분증 | 납부내역증명(납세사실증명) | 납세증명서(국세완납증명) | 지방세납세증명서 | 기량검증 확인서(해당 직종)',
        'exceptions_summary': '특정활동(E-7)은 외국인등록 시 직업 및 연간소득금액 신고 대상 / 기량검증 필요 직종은 현지 기량검증통과 확인서 제출 / 만 6세~18세 재학 중인 경우 재학증명서 제출 / 결핵고위험국가 조건 해당 시 결핵진단서 추가 가능',
        'fee_rule': '외국인등록증 발급 및 재발급 3만 5천원',
        'basis_file': '260310 체류민원 자격별 안내 매뉴얼.pdf',
        'basis_section': '외국인등록|출입국관리법 시행규칙 제47조·제49조의2·제72조|260310 체류민원 자격별 안내 매뉴얼 특정활동(E-7) 일반기능인력(E-7-3)',
        'status': 'active',
    },
    {
        'row_id': 'M1-0318',
        'domain': '체류민원',
        'major_action_std': '재입국허가',
        'action_type': 'REENTRY',
        'business_name': '일반기능인력',
        'detailed_code': 'E-7-3',
        'overview_short': '특정활동(E-7-3) 자격의 재입국허가 업무',
        'form_docs': '통합신청서(별지34호서식) | 위임장',
        'supporting_docs': '여권 | 외국인등록증 | 고용계약서 | 신원보증인 신분증 | 납부내역증명(납세사실증명) | 납세증명서(국세완납증명) | 지방세납세증명서 | 사업자등록증',
        'exceptions_summary': '등록을 필한 외국인이 출국한 날부터 1년 이내 재입국하려는 경우 재입국허가 면제 / 체류기간이 1년보다 적게 남아있는 경우 체류기간 범위 내 면제 / 입국규제자 및 사증발급규제자는 재입국허가 필요',
        'fee_rule': '단수 3만원 | 복수 5만원',
        'basis_file': '260310 체류민원 자격별 안내 매뉴얼.pdf',
        'basis_section': '재입국허가|260310 체류민원 자격별 안내 매뉴얼 공통 재입국허가',
        'status': 'active',
    },
    {
        'row_id': 'M1-0319',
        'domain': '체류민원',
        'major_action_std': '사증발급인정서',
        'action_type': 'VISA_CONFIRM',
        'business_name': '일반기능인력',
        'detailed_code': 'E-7-3',
        'overview_short': '특정활동(E-7-3) 일반기능인력 자격 사증발급인정서 발급 업무',
        'form_docs': '사증발급인정서 신청서(별지17호서식) | 위임장',
        'supporting_docs': '여권 사본 | 표준규격사진 1매 | 고용계약서 | 사업자등록증 | 고용추천서(산업통상자원부 등) | 기량검증 확인서(해당 직종) | 경력증명서',
        'exceptions_summary': 'E-7-3 허용 직종 범위 내에서만 발급 / 기량검증 필요 직종은 현지 기량검증 통과 후 신청 가능 / 국민고용비율 준수 / 사회통합프로그램 조건 적용',
        'fee_rule': '수수료 없음 (사증발급인정서)',
        'basis_file': '260310 체류민원 자격별 안내 매뉴얼.pdf',
        'basis_section': '사증발급인정서|260310 체류민원 자격별 안내 매뉴얼 특정활동(E-7) 일반기능인력(E-7-3)',
        'status': 'active',
    },

    # ─────────────── E-7-S 네거티브방식 전문인력 ───────────────
    {
        'row_id': 'M1-0320',
        'domain': '체류민원',
        'major_action_std': '체류자격 변경허가',
        'action_type': 'CHANGE',
        'business_name': '네거티브방식 전문인력',
        'detailed_code': 'E-7-S',
        'overview_short': '네거티브방식(E-7-S) 전문인력 자격으로 변경하려는 외국인의 체류자격 변경 업무 (E-7-S1: 고소득자, E-7-S2: 첨단산업분야)',
        'form_docs': '통합신청서(별지34호서식) | 위임장 | 대행업무수행확인서 | 외국인 직업 신고서',
        'supporting_docs': '여권 | 외국인등록증 | 고용계약서 | 소득증명(전년도 1인당 GNI 3배 이상; E-7-S1) 또는 점수제 심사표·첨단산업분야 종사 입증서류(E-7-S2) | 사업자등록증 | 체류지 입증서류 | 재직증명서 또는 사업자등록증 사본',
        'exceptions_summary': 'E-7-S1 고소득자: 소득이 전년도 1인당 국민총소득(GNI)의 3배 이상인 전문인력, 제한되는 직종에 취업하지 않을 것 / E-7-S2 첨단산업분야: 첨단산업발전법 제5조 및 첨단기술제품 범위 고시된 분야, 점수 60점 이상, 소득 GNI 1배 이상 / E-7-S로 국내에서 1년 이상 체류한 자는 점수제 거주(F-2-7) 자격변경 가능',
        'fee_rule': '수수료 없음 (체류자격 변경허가)',
        'basis_file': '260310 체류민원 자격별 안내 매뉴얼.pdf',
        'basis_section': '출입국관리법 제24조|260310 체류민원 자격별 안내 매뉴얼 네거티브방식의 전문인력 비자(E-7-S)',
        'status': 'active',
    },
    {
        'row_id': 'M1-0321',
        'domain': '체류민원',
        'major_action_std': '체류기간 연장허가',
        'action_type': 'EXTEND',
        'business_name': '네거티브방식 전문인력',
        'detailed_code': 'E-7-S',
        'overview_short': '네거티브방식(E-7-S) 전문인력 자격으로 계속 활동하려는 외국인의 체류기간 연장 업무',
        'form_docs': '통합신청서(별지34호서식) | 위임장 | 대행업무수행확인서 | 외국인 직업 신고서',
        'supporting_docs': '여권 원본 | 외국인등록증 | 표준규격사진 1매 | 고용계약서 사본 또는 재직증명서 | 소득증명(전년도 개인소득금액증명 필수) | 사업자등록증 | 체류지 입증서류 | E-7-S2의 경우 첨단산업분야 종사 지속 입증서류',
        'exceptions_summary': 'E-7-S1 고소득자: 소득이 GNI 3배 이상 유지 필요 / E-7-S2: 점수 60점 이상 및 첨단산업분야 종사 지속 / 여권 유효기간 범위 내 체류기간 부여 / 결핵고위험국가 조건 해당 시 결핵진단서 추가 가능',
        'fee_rule': '수수료 없음 (체류기간 연장허가)',
        'basis_file': '260310 체류민원 자격별 안내 매뉴얼.pdf',
        'basis_section': '출입국관리법 제25조|260310 체류민원 자격별 안내 매뉴얼 네거티브방식의 전문인력 비자(E-7-S)',
        'status': 'active',
    },
    {
        'row_id': 'M1-0322',
        'domain': '체류민원',
        'major_action_std': '외국인등록',
        'action_type': 'REGISTRATION',
        'business_name': '네거티브방식 전문인력',
        'detailed_code': 'E-7-S',
        'overview_short': '네거티브방식(E-7-S) 자격으로 입국하거나 체류자격을 받은 외국인의 외국인등록 업무',
        'form_docs': '통합신청서(별지34호서식) | 위임장 | 외국인 직업 신고서',
        'supporting_docs': '여권 원본 | 표준규격사진 1매 | 사업자등록증 | 고용계약서 | 체류지 입증서류 | 체류자격부여/변경 허가서 또는 입국 사증 | 소득증명(E-7-S1) 또는 점수제 심사표(E-7-S2)',
        'exceptions_summary': '특정활동(E-7)은 외국인등록 시 직업 및 연간소득금액 신고 대상 / 결핵고위험국가 조건 해당 시 결핵진단서 추가 가능',
        'fee_rule': '외국인등록증 발급 및 재발급 3만 5천원',
        'basis_file': '260310 체류민원 자격별 안내 매뉴얼.pdf',
        'basis_section': '외국인등록|260310 체류민원 자격별 안내 매뉴얼 네거티브방식의 전문인력 비자(E-7-S)',
        'status': 'active',
    },
    {
        'row_id': 'M1-0323',
        'domain': '체류민원',
        'major_action_std': '재입국허가',
        'action_type': 'REENTRY',
        'business_name': '네거티브방식 전문인력',
        'detailed_code': 'E-7-S',
        'overview_short': '네거티브방식(E-7-S) 자격의 재입국허가 업무',
        'form_docs': '통합신청서(별지34호서식) | 위임장',
        'supporting_docs': '여권 | 외국인등록증 | 고용계약서 | 사업자등록증',
        'exceptions_summary': '등록을 필한 외국인이 출국한 날부터 1년 이내 재입국하려는 경우 재입국허가 면제 / 체류기간이 1년보다 적게 남아있는 경우 체류기간 범위 내 면제',
        'fee_rule': '단수 3만원 | 복수 5만원',
        'basis_file': '260310 체류민원 자격별 안내 매뉴얼.pdf',
        'basis_section': '재입국허가|260310 체류민원 자격별 안내 매뉴얼',
        'status': 'active',
    },
    {
        'row_id': 'M1-0324',
        'domain': '사증민원',
        'major_action_std': '사증발급',
        'action_type': 'GRANT',
        'business_name': '네거티브방식 전문인력',
        'detailed_code': 'E-7-S',
        'overview_short': '네거티브방식(E-7-S) 전문인력 사증발급 업무 (E-7-S1: 고소득자, E-7-S2: 첨단산업분야)',
        'form_docs': '사증발급신청서 | 여권',
        'supporting_docs': '표준규격사진 1매 | 고용계약서 | 사업자등록증 | 소득증명(GNI 3배 이상; E-7-S1) 또는 점수제 심사표·첨단산업분야 종사 입증서류(E-7-S2) | 학위증 또는 경력증명서',
        'exceptions_summary': 'E-7-S1 고소득자: 소득이 전년도 1인당 GNI 3배 이상, 제한 직종 취업 불가 / E-7-S2 첨단산업분야: 첨단산업발전법 고시 분야, 점수 60점 이상, 소득 GNI 1배 이상 / 국민고용비율 비해당(비용) / 재외공관 또는 출입국에서 처리',
        'fee_rule': '재외공관 사증 수수료 별도',
        'basis_file': '260310 체류민원 자격별 안내 매뉴얼.pdf|260310 사증민원 자격별 안내 매뉴얼.pdf',
        'basis_section': '260310 체류민원 자격별 안내 매뉴얼 네거티브방식의 전문인력 비자(E-7-S)|260310 사증민원 자격별 안내 매뉴얼 특정활동(E-7)',
        'status': 'active',
    },

    # ─────────────── E-7-Y 국내성장인력 ───────────────
    {
        'row_id': 'M1-0325',
        'domain': '체류민원',
        'major_action_std': '체류자격 변경허가',
        'action_type': 'CHANGE',
        'business_name': '국내성장인력',
        'detailed_code': 'E-7-Y',
        'overview_short': '국내에서 성장한 외국인(국내성장인력, E-7-Y)이 특정활동 직종에 종사하려는 체류자격 변경 업무. 직종코드 9999 적용.',
        'form_docs': '통합신청서(별지34호서식) | 위임장 | 대행업무수행확인서 | 외국인 직업 신고서',
        'supporting_docs': '여권 | 외국인등록증 | 고용계약서 | 국내 학력 입증서류(졸업증명서 등) | 사업자등록증 | 체류지 입증서류 | 체류경력 입증서류(국내 성장 이력)',
        'exceptions_summary': '국내성장인력(E-7-Y): 국내에서 초·중·고 또는 대학교육을 이수하고 성장한 외국인 / 직종코드 9999 / 기존 E-7-3 일반기능인력의 사회통합프로그램 이수 조건 등 일부 특례 적용 / 국민고용비율 준수',
        'fee_rule': '수수료 없음 (체류자격 변경허가)',
        'basis_file': '260310 체류민원 자격별 안내 매뉴얼.pdf',
        'basis_section': '출입국관리법 제24조|260310 체류민원 자격별 안내 매뉴얼 특정활동(E-7) 국내성장인력(E-7-Y)',
        'status': 'active',
    },
    {
        'row_id': 'M1-0326',
        'domain': '체류민원',
        'major_action_std': '체류기간 연장허가',
        'action_type': 'EXTEND',
        'business_name': '국내성장인력',
        'detailed_code': 'E-7-Y',
        'overview_short': '특정활동(E-7-Y) 국내성장인력 자격으로 계속 활동하려는 외국인의 체류기간 연장 업무',
        'form_docs': '통합신청서(별지34호서식) | 위임장 | 대행업무수행확인서 | 외국인 직업 신고서',
        'supporting_docs': '여권 원본 | 외국인등록증 | 표준규격사진 1매 | 고용계약서 사본 또는 재직증명서 | 연간소득 입증서류(개인소득금액증명 필수) | 사업자등록증 | 체류지 입증서류',
        'exceptions_summary': '여권 유효기간 범위 내 체류기간 부여 / 결핵고위험국가 조건 해당 시 결핵진단서 추가 가능 / 국내성장인력 특례 적용(E-7-3 사회통합프로그램 이수 조건 완화)',
        'fee_rule': '수수료 없음 (체류기간 연장허가)',
        'basis_file': '260310 체류민원 자격별 안내 매뉴얼.pdf',
        'basis_section': '출입국관리법 제25조|260310 체류민원 자격별 안내 매뉴얼 특정활동(E-7) 국내성장인력(E-7-Y)',
        'status': 'active',
    },
    {
        'row_id': 'M1-0327',
        'domain': '체류민원',
        'major_action_std': '외국인등록',
        'action_type': 'REGISTRATION',
        'business_name': '국내성장인력',
        'detailed_code': 'E-7-Y',
        'overview_short': '특정활동(E-7-Y) 국내성장인력 자격으로 입국하거나 체류자격을 받은 외국인의 외국인등록 업무',
        'form_docs': '통합신청서(별지34호서식) | 위임장 | 외국인 직업 신고서',
        'supporting_docs': '여권 원본 | 표준규격사진 1매 | 사업자등록증 | 고용계약서 | 체류지 입증서류 | 체류자격부여/변경 허가서 또는 입국 사증 | 국내 학력 입증서류',
        'exceptions_summary': '특정활동(E-7)은 외국인등록 시 직업 및 연간소득금액 신고 대상 / 국내 성장 이력(학교생활) 입증 필요 / 결핵고위험국가 조건 해당 시 결핵진단서 추가 가능',
        'fee_rule': '외국인등록증 발급 및 재발급 3만 5천원',
        'basis_file': '260310 체류민원 자격별 안내 매뉴얼.pdf',
        'basis_section': '외국인등록|260310 체류민원 자격별 안내 매뉴얼 특정활동(E-7) 국내성장인력(E-7-Y)',
        'status': 'active',
    },
    {
        'row_id': 'M1-0328',
        'domain': '체류민원',
        'major_action_std': '재입국허가',
        'action_type': 'REENTRY',
        'business_name': '국내성장인력',
        'detailed_code': 'E-7-Y',
        'overview_short': '특정활동(E-7-Y) 국내성장인력 자격의 재입국허가 업무',
        'form_docs': '통합신청서(별지34호서식) | 위임장',
        'supporting_docs': '여권 | 외국인등록증 | 고용계약서 | 사업자등록증',
        'exceptions_summary': '등록을 필한 외국인이 출국한 날부터 1년 이내 재입국하려는 경우 재입국허가 면제 / 체류기간이 1년보다 적게 남아있는 경우 체류기간 범위 내 면제',
        'fee_rule': '단수 3만원 | 복수 5만원',
        'basis_file': '260310 체류민원 자격별 안내 매뉴얼.pdf',
        'basis_section': '재입국허가|260310 체류민원 자격별 안내 매뉴얼',
        'status': 'active',
    },

    # ─────────────── E-7-T 최우수인재 (REENTRY, REGISTRATION 추가) ───────────────
    {
        'row_id': 'M1-0329',
        'domain': '체류민원',
        'major_action_std': '외국인등록',
        'action_type': 'REGISTRATION',
        'business_name': '최우수인재',
        'detailed_code': 'E-7-T',
        'overview_short': '특정활동(E-7-T) 최우수인재 자격으로 입국하거나 체류자격을 받은 외국인의 외국인등록 업무',
        'form_docs': '통합신청서(별지34호서식) | 위임장 | 외국인 직업 신고서',
        'supporting_docs': '여권 원본 | 표준규격사진 1매 | 고용계약서 | 사업자등록증 | 숙소제공확인서 | 신원보증서 | 체류자격부여/변경 허가서 또는 입국 사증 | 체류지 입증서류',
        'exceptions_summary': 'E-7-T 최우수인재 자격은 첨단산업분야 최우수인재(타임즈선정 200대 대학 등) / 특별 혜택: 비자발급·체류 관련 우대 / 결핵고위험국가 조건 해당 시 결핵진단서 추가 가능',
        'fee_rule': '외국인등록증 발급 및 재발급 3만 5천원',
        'basis_file': '260310 체류민원 자격별 안내 매뉴얼.pdf',
        'basis_section': '외국인등록|260310 체류민원 자격별 안내 매뉴얼 특정활동(E-7) 최우수인재(E-7-T)',
        'status': 'active',
    },
    {
        'row_id': 'M1-0330',
        'domain': '체류민원',
        'major_action_std': '재입국허가',
        'action_type': 'REENTRY',
        'business_name': '최우수인재',
        'detailed_code': 'E-7-T',
        'overview_short': '특정활동(E-7-T) 최우수인재 자격의 재입국허가 업무',
        'form_docs': '통합신청서(별지34호서식) | 위임장',
        'supporting_docs': '여권 | 외국인등록증 | 고용계약서 | 신원보증서 | 사업자등록증',
        'exceptions_summary': '등록을 필한 외국인이 출국한 날부터 1년 이내 재입국하려는 경우 재입국허가 면제 / 체류기간이 1년보다 적게 남아있는 경우 체류기간 범위 내 면제',
        'fee_rule': '단수 3만원 | 복수 5만원',
        'basis_file': '260310 체류민원 자격별 안내 매뉴얼.pdf',
        'basis_section': '재입국허가|260310 체류민원 자격별 안내 매뉴얼',
        'status': 'active',
    },

    # ─────────────── E-7-4 REGISTRATION (숙련기능인력 K-point 최초 등록) ───────────────
    {
        'row_id': 'M1-0331',
        'domain': '체류민원',
        'major_action_std': '외국인등록',
        'action_type': 'REGISTRATION',
        'business_name': '숙련기능인력(점수제)',
        'detailed_code': 'E-7-4',
        'overview_short': '숙련기능인력(점수제, E-7-4) 자격 변경 후 외국인등록 업무 (K-point E74 체계)',
        'form_docs': '통합신청서(별지34호서식) | 위임장 | 외국인 직업 신고서',
        'supporting_docs': '여권 원본 | 표준규격사진 1매 | 고용계약서(E-7-4 표준근로계약서 견본 참조) | 사업자등록증 또는 농업경영체등록(농업인 경우) | 체류자격 변경 허가서 | 체류지 입증서류 | 납세증명서·지방세납세증명서 | 4대보험 사업장 가입자 명부',
        'exceptions_summary': 'K-point E74: 최근 10년간 E-9·E-10·H-2 자격으로 4년 이상 체류한 현 등록외국인, 현재 근무처에서 연봉 2,600만원 이상, 향후 2년 이상 E-7-4 고용계약 / E-7-4로 자격변경 된 경우 등록 필수 / 결핵고위험국가 조건 해당 시 결핵진단서 추가 가능',
        'fee_rule': '외국인등록증 발급 및 재발급 3만 5천원',
        'basis_file': '260310 체류민원 자격별 안내 매뉴얼.pdf',
        'basis_section': '외국인등록|260310 체류민원 자격별 안내 매뉴얼 숙련기능인력(E-7-4) 체류관리 안내 매뉴얼',
        'status': 'active',
    },
]

# ─── Write to Excel ───────────────────────────────────────────────
wb = openpyxl.load_workbook(EXCEL_PATH)
ws = wb['MASTER_ROWS']
headers = [c.value for c in ws[1]]

added = 0
for row_data in new_rows:
    row_values = [row_data.get(h, '') for h in headers]
    ws.append(row_values)
    added += 1
    print(f'Added: {row_data["row_id"]} {row_data["detailed_code"]} {row_data["action_type"]}')

wb.save(EXCEL_PATH)
print(f'\nTotal rows added: {added}')
print(f'Excel total rows (incl header): {ws.max_row}')
