FROM node:20-alpine AS deps
WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN npm install

FROM node:20-alpine AS builder
WORKDIR /app/frontend
COPY --from=deps /app/frontend/node_modules ./node_modules
COPY frontend ./
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app/frontend

ENV NODE_ENV=production
ENV PORT=3000

COPY --from=builder /app/frontend ./

EXPOSE 3000

CMD ["npm", "run", "start"]