"""0002 customers events memos daily tasks

Revision ID: 62a63fa57573
Revises: f6e365d01243
Create Date: 2026-06-02 00:09:50.011094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62a63fa57573'
down_revision: Union[str, Sequence[str], None] = 'f6e365d01243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('date', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('work', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('transfer', sa.Text(), nullable=True),
    sa.Column('cash', sa.Text(), nullable=True),
    sa.Column('card', sa.Text(), nullable=True),
    sa.Column('stamp', sa.Text(), nullable=True),
    sa.Column('receivable', sa.Text(), nullable=True),
    sa.Column('planned_expense', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('processed_timestamp', sa.Text(), nullable=True),
    sa.Column('reception', sa.Text(), nullable=True),
    sa.Column('processing', sa.Text(), nullable=True),
    sa.Column('storage', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.Text(), nullable=True),
    sa.Column('source_daily_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'task_id', name='uq_active_task_per_tenant')
    )
    op.create_index('idx_active_tenant_date', 'active_tasks', ['tenant_id', 'date'], unique=False)
    op.create_table('completed_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('date', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('work', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('complete_date', sa.Text(), nullable=True),
    sa.Column('reception', sa.Text(), nullable=True),
    sa.Column('processing', sa.Text(), nullable=True),
    sa.Column('storage', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'task_id', name='uq_completed_task_per_tenant')
    )
    op.create_index('idx_completed_tenant_customer', 'completed_tasks', ['tenant_id', 'customer_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.Text(), nullable=False),
    sa.Column('korean_name', sa.Text(), nullable=True),
    sa.Column('surname_en', sa.Text(), nullable=True),
    sa.Column('given_en', sa.Text(), nullable=True),
    sa.Column('passport_no', sa.Text(), nullable=True),
    sa.Column('nationality', sa.Text(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('reg_front', sa.Text(), nullable=True),
    sa.Column('reg_back', sa.Text(), nullable=True),
    sa.Column('card_issue_date', sa.Text(), nullable=True),
    sa.Column('card_expiry_date', sa.Text(), nullable=True),
    sa.Column('passport_issue_date', sa.Text(), nullable=True),
    sa.Column('passport_expiry_date', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone1', sa.Text(), nullable=True),
    sa.Column('phone2', sa.Text(), nullable=True),
    sa.Column('phone3', sa.Text(), nullable=True),
    sa.Column('v_status', sa.Text(), nullable=True),
    sa.Column('visa_status', sa.Text(), nullable=True),
    sa.Column('visa_type', sa.Text(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('folder_id', sa.Text(), nullable=True),
    sa.Column('delegation_history', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'customer_id', name='uq_customer_per_tenant')
    )
    op.create_index('idx_customers_card_expiry', 'customers', ['card_expiry_date'], unique=False)
    op.create_index('idx_customers_passport_expiry', 'customers', ['passport_expiry_date'], unique=False)
    op.create_index('idx_customers_tenant_alive', 'customers', ['tenant_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('daily_balances',
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('cash', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('profit', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('daily_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('entry_id', sa.Text(), nullable=False),
    sa.Column('date', sa.Text(), nullable=True),
    sa.Column('time', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('task', sa.Text(), nullable=True),
    sa.Column('income_cash', sa.Integer(), server_default='0', nullable=False),
    sa.Column('income_etc', sa.Integer(), server_default='0', nullable=False),
    sa.Column('exp_cash', sa.Integer(), server_default='0', nullable=False),
    sa.Column('exp_etc', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cash_out', sa.Integer(), server_default='0', nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'entry_id', name='uq_daily_entry_per_tenant')
    )
    op.create_index('idx_daily_tenant_date', 'daily_entries', ['tenant_id', 'date'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('date_str', sa.Text(), nullable=False),
    sa.Column('event_text', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_tenant_date', 'events', ['tenant_id', 'date_str'], unique=False)
    op.create_table('memos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('short', 'mid', 'long')", name='ck_memo_kind'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'kind', name='uq_memo_per_tenant_kind')
    )
    op.create_table('planned_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('date', sa.Text(), nullable=True),
    sa.Column('period', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'task_id', name='uq_planned_task_per_tenant')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planned_tasks')
    op.drop_table('memos')
    op.drop_index('idx_events_tenant_date', table_name='events')
    op.drop_table('events')
    op.drop_index('idx_daily_tenant_date', table_name='daily_entries')
    op.drop_table('daily_entries')
    op.drop_table('daily_balances')
    op.drop_index('idx_customers_tenant_alive', table_name='customers', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_customers_passport_expiry', table_name='customers')
    op.drop_index('idx_customers_card_expiry', table_name='customers')
    op.drop_table('customers')
    op.drop_index('idx_completed_tenant_customer', table_name='completed_tasks')
    op.drop_table('completed_tasks')
    op.drop_index('idx_active_tenant_date', table_name='active_tasks')
    op.drop_table('active_tasks')
    # ### end Alembic commands ###
