"""0003 signatures relationships board marketing cert work_ref docs

Revision ID: a9e88d5f778a
Revises: 62a63fa57573
Create Date: 2026-06-02 10:05:12.933385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9e88d5f778a'
down_revision: Union[str, Sequence[str], None] = '62a63fa57573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_comments',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('post_id', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=True),
    sa.Column('author_login', sa.Text(), nullable=True),
    sa.Column('office_name', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('db_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_comments_post_id'), 'board_comments', ['post_id'], unique=False)
    op.create_table('board_posts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=True),
    sa.Column('author_login', sa.Text(), nullable=True),
    sa.Column('office_name', sa.Text(), nullable=True),
    sa.Column('is_notice', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('popup_yn', sa.Text(), nullable=True),
    sa.Column('link_url', sa.Text(), nullable=True),
    sa.Column('comment_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('db_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_board_posts_category', 'board_posts', ['category'], unique=False)
    op.create_table('cert_directions',
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('active', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cert_directions_tenant', 'cert_directions', ['tenant_id'], unique=False)
    op.create_table('cert_groups',
    sa.Column('group_name', sa.Text(), nullable=True),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.Column('default_direction', sa.Text(), nullable=True),
    sa.Column('applicable_directions', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('active', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cert_groups_tenant', 'cert_groups', ['tenant_id'], unique=False)
    op.create_table('cert_prices',
    sa.Column('vendor_id', sa.Text(), nullable=True),
    sa.Column('group_id', sa.Text(), nullable=True),
    sa.Column('direction', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('price', sa.Text(), nullable=True),
    sa.Column('possible', sa.Text(), nullable=True),
    sa.Column('documents', sa.Text(), nullable=True),
    sa.Column('lead_time', sa.Text(), nullable=True),
    sa.Column('strength', sa.Text(), nullable=True),
    sa.Column('risk', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('last_checked', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('active', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cert_prices_tenant', 'cert_prices', ['tenant_id'], unique=False)
    op.create_table('cert_regions',
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('applicable_directions', sa.Text(), nullable=True),
    sa.Column('applicable_group_ids', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('active', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cert_regions_tenant', 'cert_regions', ['tenant_id'], unique=False)
    op.create_table('cert_vendors',
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('contact', sa.Text(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('active', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cert_vendors_tenant', 'cert_vendors', ['tenant_id'], unique=False)
    op.create_table('marketing_posts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Text(), nullable=True),
    sa.Column('is_featured', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('image_file_id', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('image_alt', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('db_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_marketing_published', 'marketing_posts', ['is_published'], unique=False)
    op.create_table('accommodation_providers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('target_customer_id', sa.Text(), nullable=False),
    sa.Column('provider_type', sa.Text(), nullable=True),
    sa.Column('provider_customer_id', sa.Text(), nullable=True),
    sa.Column('provider_name', sa.Text(), nullable=True),
    sa.Column('provider_last_name', sa.Text(), nullable=True),
    sa.Column('provider_first_name', sa.Text(), nullable=True),
    sa.Column('provider_nation', sa.Text(), nullable=True),
    sa.Column('provider_reg_front', sa.Text(), nullable=True),
    sa.Column('provider_reg_back', sa.Text(), nullable=True),
    sa.Column('provider_birth', sa.Text(), nullable=True),
    sa.Column('provider_phone', sa.Text(), nullable=True),
    sa.Column('provider_address', sa.Text(), nullable=True),
    sa.Column('provider_relation', sa.Text(), nullable=True),
    sa.Column('provide_start_date', sa.Text(), nullable=True),
    sa.Column('provide_end_date', sa.Text(), nullable=True),
    sa.Column('housing_type', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'target_customer_id', name='uq_accommodation_per_target')
    )
    op.create_table('agent_signatures',
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('signature_data', sa.Text(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('customer_signatures',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.Text(), nullable=False),
    sa.Column('signature_data', sa.Text(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'customer_id', name='uq_customer_signature')
    )
    op.create_table('document_metadata',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.Text(), nullable=True),
    sa.Column('drive_file_id', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('doc_type', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_docs_tenant_customer', 'document_metadata', ['tenant_id', 'customer_id'], unique=False)
    op.create_table('guarantor_connections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('target_customer_id', sa.Text(), nullable=False),
    sa.Column('guarantor_type', sa.Text(), nullable=True),
    sa.Column('guarantor_customer_id', sa.Text(), nullable=True),
    sa.Column('guarantor_name', sa.Text(), nullable=True),
    sa.Column('guarantor_last_name', sa.Text(), nullable=True),
    sa.Column('guarantor_first_name', sa.Text(), nullable=True),
    sa.Column('guarantor_nation', sa.Text(), nullable=True),
    sa.Column('guarantor_reg_front', sa.Text(), nullable=True),
    sa.Column('guarantor_reg_back', sa.Text(), nullable=True),
    sa.Column('guarantor_birth', sa.Text(), nullable=True),
    sa.Column('guarantor_phone', sa.Text(), nullable=True),
    sa.Column('guarantor_address', sa.Text(), nullable=True),
    sa.Column('guarantor_relation', sa.Text(), nullable=True),
    sa.Column('guarantor_workplace', sa.Text(), nullable=True),
    sa.Column('guarantor_extra', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'target_customer_id', name='uq_guarantor_per_target')
    )
    op.create_table('temp_signature_slots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('signature_data', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('slot IN (1, 2, 3)', name='ck_temp_slot_range'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slot', name='uq_temp_slot_per_tenant')
    )
    op.create_table('work_reference_rows',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('sheet_name', sa.Text(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'sheet_name', 'row_index', name='uq_work_ref_row')
    )
    op.create_index('idx_work_ref_rows_lookup', 'work_reference_rows', ['tenant_id', 'sheet_name', 'row_index'], unique=False)
    op.create_table('work_reference_sheets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('sheet_name', sa.Text(), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'sheet_name', name='uq_work_ref_sheet_per_tenant')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_reference_sheets')
    op.drop_index('idx_work_ref_rows_lookup', table_name='work_reference_rows')
    op.drop_table('work_reference_rows')
    op.drop_table('temp_signature_slots')
    op.drop_table('guarantor_connections')
    op.drop_index('idx_docs_tenant_customer', table_name='document_metadata')
    op.drop_table('document_metadata')
    op.drop_table('customer_signatures')
    op.drop_table('agent_signatures')
    op.drop_table('accommodation_providers')
    op.drop_index('idx_marketing_published', table_name='marketing_posts')
    op.drop_table('marketing_posts')
    op.drop_index('idx_cert_vendors_tenant', table_name='cert_vendors')
    op.drop_table('cert_vendors')
    op.drop_index('idx_cert_regions_tenant', table_name='cert_regions')
    op.drop_table('cert_regions')
    op.drop_index('idx_cert_prices_tenant', table_name='cert_prices')
    op.drop_table('cert_prices')
    op.drop_index('idx_cert_groups_tenant', table_name='cert_groups')
    op.drop_table('cert_groups')
    op.drop_index('idx_cert_directions_tenant', table_name='cert_directions')
    op.drop_table('cert_directions')
    op.drop_index('idx_board_posts_category', table_name='board_posts')
    op.drop_table('board_posts')
    op.drop_index(op.f('ix_board_comments_post_id'), table_name='board_comments')
    op.drop_table('board_comments')
    # ### end Alembic commands ###
